name: CICD - ERP Base v13.0

on:
  push:
    branches: [ 13.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build erp base
        run: |
          docker build -f ./docker/Dockerfile -t $DOCKER_USER/erp-base:13.0-latest .
      - name: docker push erp base latest
        run: |
          docker push $DOCKER_USER/erp-base:13.0-latest
      - name: docker cp erp base
        run: |
          docker tag erp-base:13.0-latest $DOCKER_USER/erp-base:13.0-${{ steps.date.outputs.date }}
      - name: docker push erp base with date
        run: |
          docker push $DOCKER_USER/erp-base:13.0-${{ steps.date.outputs.date }}